### ISSUE TITLE
state=set does not set properties.

### ISSUE THREAD

**Issue by vbotka** [fractalcells/ansible-iocage#30]
The default value of stop_timeout is 30
```
# iocage get stop_timeout test_31
30
```
The single test
```
ansible-playbook iocage_test.yml -M . -e 'debug=true debug2=true' -t base_set
```

```yaml
- name: Verify that base jail can be converted
  block:
    - name: Verify that base jail can be converted
      iocage:
        state: set
        name: test_31
#      name: "{{ basejail }}"
        properties:
          stop_timeout: 35
#         template: 'no'
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result
```

does not set the value.

```yaml
    changed: false
    failed: false
    msg: properties dict_keys(['stop_timeout']) already set for jail test_31
```

```
# iocage get stop_timeout test_31
30
```
