### ISSUE TITLE
state=cloned and clone_from does not work with Python 3.8

### ISSUE THREAD

**Issue by vbotka** [fractalcells/ansible-iocage#32]
test base_clone

```yaml
  - iocage:
       state: cloned
       name: "{{ jname }}"
       clone_from: "{{ basejail }}"
```

> fatal: [localhost]: FAILED! => changed=false 
  msg: |-
    Jail 'test_jail' could not be created.
    cmd: '/usr/local/bin/iocage clone test_basejail_13_0_RELEASE -n test_jail ' return: 1
    stdout: ''
    stderr: 'Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/iocage_lib/ioc_create.py", line 264, in _create_jail
        su.check_call(snap_cmd, stderr=su.PIPE)
      File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['zfs', 'snapshot', '-r', 'zroot/iocage/jails/test_basejail_13_0_RELEASE@test_jail']' returned non-zero exit status 1.
  
>   During handling of the above exception, another exception occurred:
  
>    Traceback (most recent call last):
      File "/usr/local/bin/iocage", line 10, in <module>
        sys.exit(cli())
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/iocage_cli/clone.py", line 71, in cli
        ioc.IOCage(jail=source, skip_jails=True).create(
      File "/usr/local/lib/python3.8/site-packages/iocage_lib/iocage.py", line 637, in create
        ioc_create.IOCCreate(
      File "/usr/local/lib/python3.8/site-packages/iocage_lib/ioc_create.py", line 98, in create_jail
        return self._create_jail(jail_uuid, location)
      File "/usr/local/lib/python3.8/site-packages/iocage_lib/ioc_create.py", line 266, in _create_jail
        raise RuntimeError(f'Jail: {jail_uuid} not found!')
    RuntimeError: Jail: test_jail not found!
    '

The node is running on bhyve  in TrueNAS-12.0-U2.1

```
Virtual CPUs:
1

Cores:
4

Threads:
4

Memory Size:
8.00 GiB

Boot Loader Type:
UEFI

System Clock:
UTC

VNC Port:
47237

Description:
FreeBSD-13.0-RELEASE

Shutdown Timeout:
90 seconds
```

Python 3.7 works fine

```
ANSIBLE_PYTHON_INTERPRETER=/usr/local/bin/python3.7 ansible-playbook iocage_test.yml -M . -e 'debug=true debug2=true' -t base_clone
```

```yaml
    changed: true
    failed: false
    msg: |-
      Jail 'test_jail' was created with properties {}.
  
      /usr/local/bin/iocage clone test_basejail_13_0_RELEASE -n test_jail
    stderr: ''
    stderr_lines: []
    stdout: ''
    stdout_lines: []
```
